Repository kubernetes101/pib-dev, pull requests merged in 2022-11, with the labels that each got.

#30 adding description for arc gitops
  labs/outer-loop-arc-gitops.md
Labels: documentation

#34 Updated Arc setup
  vm/setup/arc-setup.sh
Labels: bug

#33 Updated canary workshop
  labs/advanced-labs/canary/README.md
  labs/images/envoyCanaryPromotion.png
  labs/images/envoyCanaryRollback.png
  labs/outer-loop-aks-azure.md
  labs/outer-loop-arc-gitops.md
  labs/outer-loop-multi-cluster.md
  labs/outer-loop.md
  templates/pib-service-canary/canary.yaml
  templates/pib-service-canary/ingressHttpProxy.yaml
Labels: documentation, enhancement

#37 install dotnet 6
  .devcontainer/on-create.sh
  README.md
Labels: bug, documentation
