Repository kubernetes101/pib-dev, pull requests merged in 2022-10, with the labels that each got.

#9 Updated from PiB
  README.md
  apps/redis/.gitops/dev/pvc.yaml
  labs/advanced-labs/voe/.gitops/dev/pvc.yaml
  labs/outer-loop-aks-azure.md
  labs/outer-loop-arc-gitops.md
  labs/outer-loop-multi-cluster.md
  labs/outer-loop-ring-deployment.md
  labs/outer-loop.md
Labels: documentation

#10 synched with upstream
  README.md
  clusters/sample-cluster.txt
  labs/advanced-labs/aks-iot/README.md
  labs/advanced-labs/aks-iot/sample-cluster.txt
  labs/advanced-labs/canary/README.md
  labs/inner-loop.md
  labs/outer-loop-aks-azure.md
  labs/outer-loop-arc-gitops.md
  labs/outer-loop-multi-cluster.md
  labs/outer-loop-ring-deployment.md
  labs/outer-loop.md
Labels: documentation

#13 updated gitops
  apps/flux-system/.gitops/dev/kustomization-flux-system.yaml
  labs/advanced-labs/monitoring/prometheus/.gitops/dev/prometheus.yaml
  labs/advanced-labs/monitoring/prometheus/README.md
Labels: bug

#15 Workshop Feedback
  README.md
  docs/academy.md
  labs/advanced-labs/canary/README.md
  labs/advanced-labs/monitoring/README.md
  labs/inner-loop-flux.md
  labs/inner-loop.md
  templates/README.md
  vm/README.md
Labels: bug, documentation

#18 Update README.md
  README.md
Labels: documentation

#19 set MY_BRANCH in CS setup
  .devcontainer/on-create.sh
  README.md
  labs/outer-loop-aks-azure.md
  labs/outer-loop-multi-cluster.md
Labels: documentation

#28 updated docs
  README.md
  labs/advanced-labs/aks-iot/README.md
Labels: documentation
